ecidadao:
  client-id: e5bd7fd3-af8c-4c99-8fa7-313abb8e2350
  client-secret: BX1kvKH8To3qrAxrkiej0WNYaRRJrOdb3idCES4Mj_zs9y_dODxCMtVg2HfxEBcq_pn2tWo1QIPnZXxcF8yz5Q
  pre-established-redirect-uri: http://agatha.planejamento.gov.br/gestaoriscos/api/login/openid
  sistema:
    dominio: agatha.planejamento.gov.br
    url-pattern-protegido: /**
    redireciona-login-sucesso: http://agatha.planejamento.gov.br
    redireciona-logout-sucesso: http://agatha.planejamento.gov.br

  # URIS dO AMBIENTE DE TESTES
  access-token-uri: https://testescp-ecidadao.estaleiro.serpro.gov.br/scp/token
  user-authorization-uri: https://testescp-ecidadao.estaleiro.serpro.gov.br/scp/authorize
  use-current-uri: false
  scope: openid



# URIS DO AMBIENTE DE PRODUÇÃO
#  access-token-uri: https://scp.brasilcidadao.gov.br/scp/token
#  user-authorization-uri: https://scp.brasilcidadao.gov.br/scp/authorize